apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-http
  labels:
    app: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-http
  template:
    metadata:
      labels:
        app: http-server-http
    spec:
      containers:
      - name: kubernetes-app
        image: kmi8000/kubernetes_multi_unhealthy:0.1.unhealthy
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service-http
spec:
  selector:
    app: http-server-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30003
  type: NodePort