apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-http-allprobes
  labels:
    app: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-http-allprobes
  template:
    metadata:
      labels:
        app: kubernetes-http-allprobes
    spec:
      containers:
      - name: kubernetes-app
        image: kmi8000/kubernetes_multi:0.1
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        startupProbe:
          exec:
            command:
            - cat
            - /server-test.py
          initialDelaySeconds: 10
          failureThreshold: 30 # (30 * 10) + 10 = 310 seconds
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - cat
            - /server-test.py
          failureThreshold: 1
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-http-allprobes-service
spec:
  selector:
    app: kubernetes-http-allprobes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30004
  type: NodePort