apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-app-manual
  labels:
    app: web-server
spec:
  containers:
  - name: kubernetes-app-image
    image: kmi8000/kubernetes_multi:0.2
    ports:
    - name: http
      containerPort: 8000
    - name: https
      containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app-manual-service
spec:
  selector:
    app: web-server
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https