apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-app-manual-1
  labels:
    app: kubernetes
    # env: prod
spec:
  containers:
  - name: kubernetes-app-1
    image: kmi8000/k8sphp_multi
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-app-manual-2
  labels:
    app: http-server
    # env: dev
spec:
  containers:
  - name: kubernetes-app-1
    image: kmi8000/k8sphp_multi
    ports:
    - containerPort: 8000