apiVersion: v1
kind: ReplicationController
metadata:
  name: kubernetes-rc
spec:
  replicas: 3
  selector:
    app: kubernetes
  template:
    metadata:
      name: kubernetes-app
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes-app-version-2-image
        image: kmi8000/k8sphp_multi
        ports:
        - containerPort: 8000