apiVersion: v1
kind: Pod
metadata:
  name: app-kubernetes-qa-1
  namespace: qa
  labels: 
     app: http-server
spec:
  containers:
  - name: app-kubernetes-container
    image: kmi8000/kubernetes_multi:0.1
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: app-kubernetes-qa-2
  namespace: qa
  labels: 
     app: http-server
spec:
  containers:
  - name: app-kubernetes-container
    image: kmi8000/kubernetes_multi:0.1
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: app-kubernetes-dev-1
  namespace: dev
  labels: 
     app: http-server
spec:
  containers:
  - name: app-kubernetes-container
    image: kmi8000/kubernetes_multi:0.1
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: app-kubernetes-dev-2
  namespace: dev
  labels: 
     app: http-server
spec:
  containers:
  - name: app-kubernetes-container
    image: kmi8000/kubernetes_multi:0.1
    ports:
    - containerPort: 8000