apiVersion: v1
kind: Pod
metadata:
  name: app-kubernetes-with-labels
  labels:
    environment: dev
    app: http-server
spec:
  containers:
  - name: app-kubernetes-container
    image: kmi8000/kubernetes_multi:0.1
    ports:
    - containerPort: 8000